### ISSUE TITLE
trVAE get_latent TypeError

### ISSUE THREAD

**Issue by chansigit** [theislab/scarches#102]
I got TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]
when I call trvae.get_latent()
what's wrong with it? my anndata.X is sparse, is that the reason?
![image](https://user-images.githubusercontent.com/18084613/160135988-fc3645fc-2b98-47df-8ef3-6b7ae0ea50d6.png)

![image](https://user-images.githubusercontent.com/18084613/160135932-297de17b-1056-4ca4-b75e-f839732eca06.png)

**Comment by Koncopd** [comment]
Hi, @chansigit ,` TRVAE` doesn't support sparse matrices, they are densified anyways, so to avoid these errors just try doing
`adata.X = adata.X.toarray()` before doing anything `TRVAE` realted if you have enough memory. If you need to preserve sparsity, you can use `sca.models.SCVI` instead of  `TRVAE`.
