### ISSUE TITLE
question on query data and reference data

### ISSUE THREAD

**Issue by YubinXie** [theislab/scarches#16]
Thanks for your amazing work. I have some general questions regarding query data and reference data.

1. In a setup that query data is 'all cell atlas' and reference is only cells from one organ. Will scArches overfit the huge number of unknown cells to reference after training? Is it epoch sensitive?

2. In a setup that reference data is 'all cell health atlas' and query is only cells from one organ + tumor. I saw the covid19 case in the paper and it seems it works well. Are there any tips on training in this setup?

3. Have you tried to train between scRNA and snRNA?

4. If I have enough GPUs, and if I only have one reference and one query. Shall I train them at the same time instead of 'fine-tuning'? I guess in this case, there is no such thing as 'fine-tunning'. Then in the setups i mentioned above, will the overfit be a problem if I train two very different dataset from sratch?

I will have a try to benchmark these questions myself and it would be great to get some insights from you. Thanks!

**Comment by M0hammadL** [comment]
hi @YubinXie  thanks for the interest.

> In a setup that query data is 'all cell atlas' and reference is only cells from one organ. Will scArches overfit the huge number of unknown cells to reference after training? Is it epoch sensitive?

Hmm, of course, that would be more challenging, because you would usually assume reference would be the bigger data which is more comprehensive. Why don't you make the all cell atlas as the reference? However, you can alos
try what you said. Usually, training query data does not require much epochs (100 epochs would be enough becasue
we have early stopped)

> In a setup that reference data is 'all cell health atlas' and query is only cells from one organ + tumor. I saw the covid19 case in the paper and it seems it works well. Are there any tips on training in this setup?
In this setting, it is really important to train the reference properly. Specifically, `alpha` parameter which controls how
merged you representations are. bigger alphas might remove some variation while small alpha might still preserve 
some batch effect so try tune alpha and number of layer (see training tips in [here](https://scarches.readthedocs.io/en/latest/training_tips.html) )

>Have you tried to train between scRNA and snRNA?
I have not but there should not be a big difference, should also function there

> If I have enough GPUs, and if I only have one reference and one query. Shall I train them at the same time instead of 'fine-tuning'? I guess in this case, there is no such thing as 'fine-tunning'. Then in the setups i mentioned above, will the overfit be a problem if I train two very different dataset from sratch?
that is the million-dollar question :)  I would say try both: integrate both of them at once and then compare
to the situation where you make one of the references and the then perform the fine-tuning step

**Comment by YubinXie** [comment]
Thanks, Mohammad!
