### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by mxposed** [theislab/scarches#21]
Hi, thank you for the great package!

Thanks for adding random seed recently. However, there are still some parts of the workflow for which I couldn't find how to fix randomness.

Currently, I have this:

```python
import scarches as sca
import scanpy as sc
import matplotlib as mpl
import scipy.sparse
import numpy as np
import pandas as pd
import os

ds = sc.read_h5ad("../../data/31scarches-habermann/habermann.h5ad")
…
adata = ds[:, ds.var.highly_variable]
network = sca.models.scArches(task_name='habermann_ref',
                              x_dimension=adata.shape[1],
                              z_dimension=10,
                              architecture=[128, 128],
                              gene_names=adata.var_names.tolist(),
                              conditions=adata.obs[condition_key].unique().tolist(),
                              alpha=0.001,
                              loss_fn='sse',
                              model_path="./models/scArches/",
                              seed=1066)
network.train(adata,
              condition_key=condition_key,
              n_epochs=200,
              batch_size=128,
              save=True,
              retrain=False)
latent_adata = network.get_latent(adata, condition_key)
latent_adata_t = network.get_latent(adata, condition_key)
```

Then,
```python
np.sum(latent_adata.X[:10, :10] == latent_adata.X[:10, :10])
np.sum(latent_adata.X[:10, :10] == latent_adata_t.X[:10, :10])
```
Outputs 100 and 0 respectively.

Is there a way to fix the result of `get_latent` call?

If you need it, I think I can create a reproducible small notebook, but it'll take time. Thank you

**Comment by M0hammadL** [comment]
Hi Nik,

This comes up due to the underlying structure of `get_latent` function. When you project a cell to latent space you have a fixed value for that cell in z, however since the model is generative, a noise term will be added to this z. Thus, you have z = `z_fix` + N(0,1) in which N(0,1) is a sample from a random Gaussian that is why you get different values every time you use  `get_latent`. There is a way to avoid this that I provide the ability to either get `z` or  `z_fix`. However, in total there should not be a big difference that avoids reproducibility.

**Comment by M0hammadL** [comment]
ok, I added a feature in which you get the fixed `z` as I explained. You need to set 
`return_mean` = `True` in network.get_latent(reference_adata,condition_key, return_mean=True)`
