### ISSUE TITLE
Errors extracting embeddings 

### ISSUE THREAD

**Issue by itamarb-cgen** [theislab/scarches#214]
Hi,
I am trying to follow the steps in https://github.com/theislab/scPoli_reproduce/blob/main/notebooks/suetal/IntegrationFinal.ipynb to predict disease severity based on the embeddings created by scPoli as described in the recent article by De Donno et al. (Nat. Methods 2023).
I am confused because the model is created by EMBEDCVAE and not by scPoli.
How is EMBEDCVAE related to scPoli and where can its documentation be found?
Also the documentation of scPoli is minimal and it is difficult to understand what is the output of the various functions, 
Sincerely,
Itamar

**Comment by moinfar** [comment]
Hi @itamarb-cgen 

EMBEDCVAE is the old name for the scPoli model before the paper was written.
Since the final code cleanup had a minimal change in class io signature, you should be able to run the scPoli model with the same parameters for constructing the model (such as condition_key, latent_dim, etc.) and training the model (such as n_epochs, eta, etc.) to get similar results. But please check and make sure the parameters are correct by comparing to the [model docs](https://docs.scarches.org/en/latest/api/models.html#scpoli).

Thanks,
Amir
