### ISSUE TITLE
Exception: set of gene names in train adata are inconsistent with class' gene_names

### ISSUE THREAD

**Issue by Sara-Jager** [theislab/scarches#22]
Dear scArches team!

Thank you for this exciting package. 

I am not a coder but thanks to your tutorial and the notebook from Nikolay Markov et al I have been able to create a model with my reference data. Unfortunately, when I try to project query data on the top of my reference data with new_network.train() I get the following error: Exception: set of gene names in train adata are inconsistent with class' gene_names

I have tried to make sure that the genes I have in the query dataset is also present in the reference dataset, but I still get the same error. I used this to make sure the query dataset (data_lin) don’t have any extra genes compared to the reference dataset (data):
data_var_names=data.var_names
data_lin2 = data_lin[:, data_lin.var_names.isin(data_var_names)]

I have extra genes in the reference dataset that I don’t have in the query dataset, but I guess that is normal?

 
Here is the full traceback:
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-28-7ece762eb184> in <module>
      5                   batch_size=512,
      6                   save=True,
----> 7                   retrain=False)

~\Anaconda\lib\site-packages\scarches\models\cvae.py in train(self, adata, condition_key, train_size, cell_type_key, n_epochs, batch_size, early_stop_limit, lr_reducer, n_per_epoch, score_filename, save, retrain, verbose)
    754             return self._train_on_batch(adata, condition_key, train_size, cell_type_key, n_epochs, batch_size,
    755                                         early_stop_limit, lr_reducer, n_per_epoch, score_filename, save, retrain,
--> 756                                         verbose)
    757 
    758     def _fit(self, adata,

~\Anaconda\lib\site-packages\scarches\models\scarches.py in _train_on_batch(self, adata, condition_key, train_size, cell_type_key, n_epochs, batch_size, early_stop_limit, lr_reducer, n_per_epoch, score_filename, save, retrain, verbose)
    423                 train_adata = train_adata[:, self.gene_names]
    424             else:
--> 425                 raise Exception("set of gene names in train adata are inconsistent with class' gene_names")
    426 
    427             if set(self.gene_names).issubset(set(valid_adata.var_names)):

Exception: set of gene names in train adata are inconsistent with class' gene_names

Thank you very much for your help,

Best regards Sara

**Comment by M0hammadL** [comment]
Hi @Sara-Jager The current ecosystem requires gene names to be the same. Thus, the query genes should be subsetted to the ones in reference otherwise set zero for the ones which are not available. For example, if you x_ref = [g1, g2, g3] and your query has x_qeury = [g1, g3] then the x_qeury should change to x_qeury = [g1, 0, g3] . More importantly, x_qeury can not include any gene name which is not included in the reference data.

**Comment by Sara-Jager** [comment]
Hi Mohammad,

Thanks for your fast response and explanation. 

This is probably a stupid question, but how do I change the x_qeury as you describe?

Thanks again
Sara

**Comment by M0hammadL** [comment]
> adata_query_new = adata_query_old[: , adata_reference. var_names] 

should work

**Comment by Sara-Jager** [comment]
Thanks Mohammed,

Unfortunately it does not seem to work. I get an error that ends with this:
'U2', 'CR524822.1', 'CAAA01205117.2', 'CAAA01205117.1', 'CAAA01098150.1', 'CAAA01064564.1', 'mt-Nd1', 'mt-Nd2', 'mt-Co1', 'mt-Co2', 'mt-Atp8', 'mt-Atp6', 'mt-Co3', 'mt-Nd3', 'mt-Nd4l', 'mt-Nd4', 'mt-Nd5', 'mt-Nd6', 'mt-Cytb', 'Vmn2r122', 'Cd99'], are not valid obs/ var names or indices."

I might be missing something simple here. Sorry.

**Comment by M0hammadL** [comment]
Unfortunately it does not seem to work. I get an error that ends with this:
'U2', 'CR524822.1', 'CAAA01205117.2', 'CAAA01205117.1', 'CAAA01098150.1', 'CAAA01064564.1', 'mt-Nd1', 'mt-Nd2', 'mt-Co1', 'mt-Co2', 'mt-Atp8', 'mt-Atp6', 'mt-Co3', 'mt-Nd3', 'mt-Nd4l', 'mt-Nd4', 'mt-Nd5', 'mt-Nd6', 'mt-Cytb', 'Vmn2r122', 'Cd99'], are not valid obs/ var names or indices."

I would say try to concantenate reference and query data object  so that scanpy does the overlap selection for you :
`query_referenxe_adata = adata_reference.concatenate(adata_query)
`and then select query data from query_referenxe_adata again:
`query = query_referenxe_adata[query_referenxe_adata.obs["batch_key] == "query", : ]
`

**Comment by Sara-Jager** [comment]
Thanks again Mohammed. 

It seems to give the desired result when using outer join like this:
query_referenxe_adata = adata_reference.concatenate(adata_query, join="outer") 
and then selecting query data from query_referenxe_adata as you describe:
query = query_referenxe_adata[query_referenxe_adata.obs["batch_key"] == "query", : ]

**Comment by M0hammadL** [comment]
@Sara-Jager  cool, happy that it worked. I will close the issue now
