### ISSUE TITLE
Semi-supervised scArches

### ISSUE THREAD

**Issue by chsher** [theislab/scarches#49]
Thank you for creating this tool. I’ve been following your vignette for semi-supervised scArches with SCANVI, with a reference dataset (1 batch) and a query dataset (1 batch). However, when I train SCANVI on the reference, it achieves prediction accuracy of only 59%. Is there anything I can do to improve the performance?

**Comment by M0hammadL** [comment]
Hey, thanks for using the model :) I would suggest you include more datasets in the reference building. There are two factors in having query integration:

1.  The reference model needs to have seen multiple dataasts in order to understand the meaning of batch 
2. The quality of the datasets are important and need to  include multiple cell types and enough cells in each batch

**Comment by chsher** [comment]
Thanks for your helpful feedback. I tried splitting the reference into two batches (10x v2 vs 10x v3 sequencing technology), but the improvement was marginal (accuracy of 61%). 

- The unsupervised trainer trains for 332 out of 500 epochs, and the semisupervised trainer trains for only 12 out of 200 epochs. Is there anything I can change about the training regime to improve performance?

- In the reference dataset, I have approximately 200k cells, 400 genes, and 95 cell types. Is this too few cells and/or too few genes given the number of cell types?

**Comment by M0hammadL** [comment]
Is the problem solved now? happy to follow up on this.

**Comment by chsher** [comment]
Thanks @M0hammadL the problem is unresolved.
